version: '3'
services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: Localpw@
    ports:
      - '63306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp:cached
      - ./rails/node_modules:/myapp/node_modules:cached
    ports:
      - "63000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local
